{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "buildachart.serviceAccountName" . }}
  labels:
{{ include "buildachart.labels" . | nindent 4 }}
{{- end -}}
